version: '3.1'

networks:
  cooperativa-network:
    driver: bridge

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cooperativa
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - cooperativa-network

  cooperativa:
    build: ./
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    networks:
      - cooperativa-network
    depends_on:
      - db

volumes:
  db_volume: